### ISSUE TITLE
be-multisvc: We force users to specify empty map for `volumes:` when their pods have no volumes

### ISSUE THREAD

**Issue by giuscri** [casavo/charts#19]
```
          volumeMounts:
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
```

We should probably change this into 
```
...
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```

**Comment by gi0baro** [comment]
@giuscri I don't follow the issue here, as the default values files contain an empty object for volumes, and thus there's no need to specify anything if you don't have volumes..

**Comment by giuscri** [comment]
OK, I just found out
```
volumes:
```
and
```
volumes: {}
```
are equivalent in YAML.

I just wonder if the fact we're passing an empty object where manifest syntax expects an empty array can be a problem but doing a quick test it doesn't seem so.
